# Generated by Django 5.1.7 on 2025-04-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default="", max_length=50, verbose_name="username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="", max_length=50, verbose_name="password"
                    ),
                ),
                (
                    "createTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "movie_id",
                    models.CharField(
                        default="", max_length=50, verbose_name="movie_id"
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="收藏cishu")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="Myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "history",
            },
        ),
    ]
